name: Update GitHub Profile Stats

on:
  workflow_dispatch:

  schedule:
    - cron: "17 3 * * *"

permissions:
  contents: write

concurrency:
  group: update-profile-stats
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate GitHub Streak
        uses: zients/github-readme-streak-stats@v2
        with:
          options: user=${{ github.repository_owner }}&theme=tokyonight&hide_border=true&card_width=900&disable_animations=false
          path: profile/streak.svg

      - name: Generate GitHub Activity
        uses: shinpr/github-profile-stats@49b5f7091182a45f3ef93923505b660c6da5f835
        with:
          username: ${{ github.repository_owner }}
          token: ${{ github.token }}
          profile: activity-consistency

      - name: Commit generated profile statistics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/

          if git diff --cached --quiet; then
            echo "No profile statistics changes."
          else
            git commit -m "Update GitHub profile statistics"
            git push
          fi
